### ISSUE TITLE
Instalation issues

### ISSUE THREAD

**Issue by clemens-fricke** [mrkwjc/ffnet#12]
I am having trouble getting the package correctly installed. 
In a completely new environment (python 3.10.14)  I called `pip install ffnet`. The installation was completed correctly, but if I want to use it, I get the following error.
```
[~/Documents/test/fnet] ○  ffnet  ffnetpy-3.10.14
> python
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ffnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr2/cfricke/.conda/envs/ffnet/lib/python3.10/site-packages/ffnet/__init__.py", line 16, in <module>
    import ffnet.fortran as fortran
  File "/usr2/cfricke/.conda/envs/ffnet/lib/python3.10/site-packages/ffnet/fortran/__init__.py", line 14, in <module>
    from . import _ffnet, _pikaia
ImportError: cannot import name '_ffnet' from partially initialized module 'ffnet.fortran' (most likely due to a circular import) (/usr2/cfricke/.conda/envs/ffnet/lib/python3.10/site-packages/ffnet/fortran/__init__.py)
>>> from ffnet import ffnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr2/cfricke/.conda/envs/ffnet/lib/python3.10/site-packages/ffnet/__init__.py", line 16, in <module>
    import ffnet.fortran as fortran
  File "/usr2/cfricke/.conda/envs/ffnet/lib/python3.10/site-packages/ffnet/fortran/__init__.py", line 14, in <module>
    from . import _ffnet, _pikaia
ImportError: cannot import name '_ffnet' from partially initialized module 'ffnet.fortran' (most likely due to a circular import) (/usr2/cfricke/.conda/envs/ffnet/lib/python3.10/site-packages/ffnet/fortran/__init__.py)
>>> 
[~/Documents/test/fnet] ○  ffnet  ffnetpy-3.10.14                                                                                                                                                        
> ls
[~/Documents/test/fnet] ○  ffnet  ffnetpy-3.10.14                                                                                                                                                        
> pip list
Package    Version
---------- -------
ffnet      0.8.6
numpy      2.0.1
pip        24.0
setuptools 69.5.1
wheel      0.43.0
```
In the previous console log, it is also shown that I opened the Python interpreter in an empty folder and the installed packages in the environment.

I chose 3.10 as the Python version since the last workflow on GitHub was done with Python 3.12, so I assumed a Python 3.x compatibility (which is hinted at in the Sourceforge docs but not specified directly), and I have another tool that has not updated to 3.12 yet.

I have also tested with `numpy<2` and `scipy` and `networkx` installed before installing `ffnet`; this produced the same error.

I have also tested with Python 3.12 which produced the same error.

I have also tested building it from the repo:
1) Creating clean environment python 3.12
2) Installing dependencies before hand `pip install numpy meson scipy networkx` (should be same as in github workflow, although python 3.12 needs meson-python according to setup.py, but it was installed in the next step automatically)
3) Install package from source via pip
```
> pip install .
Processing /usr2/cfricke/Documents/git/ffnet
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages (from ffnet==0.8.6) (2.0.1)
Requirement already satisfied: meson in /usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages (from ffnet==0.8.6) (1.5.1)
Collecting meson-python (from ffnet==0.8.6)
  Using cached meson_python-0.16.0-py3-none-any.whl.metadata (4.1 kB)
Collecting packaging>=19.0 (from meson-python->ffnet==0.8.6)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pyproject-metadata>=0.7.1 (from meson-python->ffnet==0.8.6)
  Using cached pyproject_metadata-0.8.0-py3-none-any.whl.metadata (3.0 kB)
Using cached meson_python-0.16.0-py3-none-any.whl (26 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pyproject_metadata-0.8.0-py3-none-any.whl (7.5 kB)
Building wheels for collected packages: ffnet
  Building wheel for ffnet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [202 lines of output]
      The Meson build system
      Version: 1.5.1
      Source dir: /workdisk/tmp/tmp3u569fez
      Build dir: /workdisk/tmp/tmp3u569fez/bbdir
      Build type: native build
      Project name: _ffnet
      Project version: 0.1
      Fortran compiler for the host machine: gfortran (gcc 12.2.0 "GNU Fortran (Debian 12.2.0-14) 12.2.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.40
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program /usr2/cfricke/.conda/envs/ffnet3/bin/python found: YES (/usr2/cfricke/.conda/envs/ffnet3/bin/python)
      Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
      Run-time dependency python found: YES 3.12
      Library quadmath found: YES
      Build targets in project: 1
      
      
      ERROR: Could not detect Ninja v1.8.2 or newer
      
      A full log can be found at /workdisk/tmp/tmp3u569fez/bbdir/meson-logs/meson-log.txt
      Cannot use distutils backend with Python>=3.12, using meson backend instead.
      Using meson backend
      Will pass --lower to f2py
      See https://numpy.org/doc/stable/f2py/buildtools/meson.html
      Reading fortran codes...
          Reading file 'ffnet.f' (format:fix,strict)
      Post-processing...
          Block: _ffnet
                          Block: prop
                          Block: sqerror
                          Block: grad
                          Block: recall
                          Block: diff
                          Block: func
                          Block: func2
                          Block: pikaiaff
                          Block: normcall
                          Block: normdiff
                          Block: normcall2
                          Block: normdiff2
                          Block: momentum
                          Block: rprop
                          Block: setin
                          Block: getout
                          Block: mapa
                          Block: dmapa
                          Block: vmapa
                          Block: mmapa
      Applying post-processing hooks...
        character_backward_compatibility_hook
      Post-processing (stage 2)...
      Building modules...
          Building module "_ffnet"...
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "prop"...
                units = prop(x,conec,units,[n,u])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "sqerror"...
                sqerr = sqerror(x,conec,units,inno,outno,input,targ,[n,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "grad"...
                xprime = grad(x,conec,bconecno,units,inno,outno,input,targ,[n,bn,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "recall"...
                output = recall(x,conec,units,inno,outno,input,[n,u,i,o])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "diff"...
                deriv = diff(x,conec,dconecno,dconecmk,units,inno,outno,input,[n,dn,u,i,o])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "func"...
                sqerr = func(x,conec,bconecno,units,inno,outno,input,targ,[n,bn,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "func2"...
                sqerr,xprime = func2(x,conec,bconecno,units,inno,outno,input,targ,[n,bn,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "pikaiaff"...
                isqerr = pikaiaff(x,ffn,conec,units,inno,outno,input,targ,bound1,bound2,[n,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "normcall"...
                output = normcall(x,conec,units,inno,outno,eni,deo,input,[n,u,i,o])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "normdiff"...
                deriv = normdiff(x,conec,dconecno,dconecmk,units,inno,outno,eni,ded,input,[n,dn,u,i,o])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "normcall2"...
                output = normcall2(x,conec,units,inno,outno,eni,deo,input,[n,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "normdiff2"...
                deriv = normdiff2(x,conec,dconecno,dconecmk,units,inno,outno,eni,ded,input,[n,dn,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "momentum"...
                x = momentum(x,conec,bconecno,units,inno,outno,input,targ,eta,moment,maxiter,[n,bn,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "rprop"...
                x,xmi = rprop(x,conec,bconecno,units,inno,outno,input,targ,a,b,mimin,mimax,xmi,maxiter,[n,bn,u,i,o,p])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "setin"...
                units = setin(input,inno,eni,units,[i,u])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "getout"...
                output = getout(units,outno,deo,[u,o])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
                  Creating wrapper for Fortran function "mapa"("mapa")...
              Constructing wrapper function "mapa"...
                mapa = mapa(f,a,b,c,d)
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
                  Creating wrapper for Fortran function "dmapa"("dmapa")...
              Constructing wrapper function "dmapa"...
                dmapa = dmapa(f,a,b,c,d)
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "vmapa"...
                vout = vmapa(vin,a,b,c,d,[n])
          Generating possibly empty wrappers"
          Maybe empty "_ffnet-f2pywrappers.f"
              Constructing wrapper function "mmapa"...
                mmout = mmapa(mmin,a,b,c,d,[m,n])
          Wrote C/API module "_ffnet" to file "./_ffnetmodule.c"
          Fortran 77 wrappers are saved to "./_ffnet-f2pywrappers.f"
      Traceback (most recent call last):
        File "/usr2/cfricke/.conda/envs/ffnet3/bin/f2py", line 8, in <module>
          sys.exit(main())
                   ^^^^^^
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 769, in main
          run_compile()
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 741, in run_compile
          builder.compile()
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 193, in compile
          self.run_meson(self.build_dir)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 186, in run_meson
          self._run_subprocess_command(setup_command, build_dir)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 182, in _run_subprocess_command
          subprocess.run(command, cwd=cwd, check=True)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['meson', 'setup', 'bbdir']' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/usr2/cfricke/Documents/git/ffnet/setup.py", line 62, in <module>
          setup(
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr2/cfricke/Documents/git/ffnet/setup.py", line 51, in run
          self.run_command('f2py')
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr2/cfricke/Documents/git/ffnet/setup.py", line 40, in run
          subprocess.check_call(cmd)
        File "/usr2/cfricke/.conda/envs/ffnet3/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['f2py', '-m', '_ffnet', '-c', 'ffnet.f']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ffnet
  Running setup.py clean for ffnet
Failed to build ffnet
ERROR: Could not build wheels for ffnet, which is required to install pyproject.toml-based projects
```

If I have overlooked something obvious I am sorry.

**Comment by clemens-fricke** [comment]
I just looked into the resolved issues and found a similar one https://github.com/mrkwjc/ffnet/issues/10#issue-2198258373. 

I have tried having meson-python installed before calling `pip install .` but it did not change the error.

**Comment by mrkwjc** [comment]
Maybe you should try to change working directory before import?

pon., 5 sie 2024, 15:37 użytkownik clemens.fricke ***@***.***>
napisał:

**Comment by mrkwjc** [comment]
Hi! 

Python 3.10
Are you sure you do `import ffnet` being in an empty directory? It seems ~/Documents/test/fnet contains `ffnet` directory.

Python 3.12
What about "ERROR: Could not detect Ninja v1.8.2 or newer"?

**Comment by clemens-fricke** [comment]
For Python 3.10 (pip install). I had already included an `ls` call in the log to show that the folder I run the commands in is empty. I am still not sure why, for at least me, the installation from pip does not work. I have actually retried the installation from pip again and made sure the work folder I started the Python interpreter was empty, but I still got the same error.

For 3.12 (source install), you were right; I did not ninja installation. After I installed it via pip it worked.
Could you please add this to the requirements in the setup file or note it in the installation instructions? I now have an installation that I can use, thank you.

**Comment by mrkwjc** [comment]
All ffnet installs are source installs :) For python 3.10 you could try master installation:

`pip install https://github.com/mrkwjc/ffnet/archive/refs/heads/master.zip`

or maybe some older version will work for you:

`pip install ffnet==0.8.4`

Unfortunately i cannot reproduce your error...

**Comment by clemens-fricke** [comment]
Ok thanks. I can work with the version that is running currently.
